networks:
  app-network:
    driver: bridge

services:
  app:
    build: .
    container_name: grafCloud-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8087"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:9.0.0
    container_name: mysql
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - './src/main/resources/db-init:/docker-entrypoint-initdb.d'
      - 'mysql-data:/var/lib/mysql'

  redis:
    image: redis:7.4.0-bookworm
    restart: unless-stopped
    container_name: redis
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server
      --save 900 1
      --loglevel warning
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$${REDIS_PASSWORD}", "--raw", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - 'redis-data:/data'

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    container_name: minio
    networks:
      - app-network
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      TZ: Europe/Moscow
    command: 'server /data --console-address ":9090" --address ":9000"'
    ports:
      - '9090:9090'
      - '9000:9000'
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - 'minio-data:/data'

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
       if ! mc ls myminio/${MINIO_BUCKET} > /dev/null 2>&1; then
         mc mb myminio/${MINIO_BUCKET};
       fi;"
    networks:
      - app-network

volumes:
  mysql-data:
    name: mysql-data
  minio-data:
    name: minio-data
  redis-data:
    name: redis-data