server:
  tomcat:
    max-swallow-size: -1
  port: ${PORT}

spring:

  session:
    redis:
      namespace: "spring:session"
      cleanup-cron: "0 0 * * * *"
    timeout: 24h

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: redis
    cache-names: redis-cache

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml
    enabled: true
    default-schema: ${DB_SCHEMA}
    drop-first: false


minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

application:
  url: ${APPLICATION_URL}
  date-pattern: ${APPLICATION_DATE_TIME_FORMAT_PATTERN}
  trash:
    retention-days: ${TRASH_RETENTION_DAYS}

logging:
  file:
    path: /var/log/grafcloud
    name: ${logging.file.path}/application.log

  level:
    root: INFO
    org.springframework: INFO
    com.project.cloud.files.storage: INFO
    io.minio: INFO
    com.zaxxer.hikari: INFO
    org.hibernate: INFO

  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 10
      total-size-cap: 250MB

  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} 
    %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"